### ISSUE TITLE
Add a visual info tool

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#259] opened 2018-10-16 15:44 UTC
# Problem

Please create a visual 'info' tool for exploring layers (perhaps like the i-button for ArcGIS?, i.e. when you click on (or hover over) an area it gives you the information. For example what water management area one is in, when exploring the Water managenemt layer. 

# Solution
Implement the info popup by doing a get feature info. We might need to create nice templates for layers coming from GeoServer

cc @gubuntu

**Comment by gubuntu** [comment] 2018-10-16 17:46
duplicate of https://github.com/kartoza/LEDET_BIMS/issues/229

@NyakudyaA please look for similar issues on LEDET or django-bims before creating new ones. And if it's functionality that both LEDET and Healthrivers need, add the issue to django-bims

and in this case it will be easier for our devs to format the response than to do a template in Geoserver

**Comment by Vries14** [comment] 2018-10-17 11:14
info popup for active layers added

**Closed by Vries14** 2018-10-17 11:14 UTC
Labels: testing
